import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { State } from "./state";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, params
}: Readonly<{
  children: React.ReactNode;
  params : any
}>) {
  return (
        <State params={params}>{children}</State>
  );
}
